### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by mariosk**
Regarding the presentations, here are some other ideas I could help:
1. Tools/Processes/Best Practices for remote development teams
2. Blockchain
3. Serverless/IPFS
4. Clean code apects

I'm adding only the first one for the next meetup.

### CODE REVIEW

**Comment by Drelos** [comment]
+1 vote from me especially for number 2 and 1

**Comment by jimmykarily** [comment]
+1 for number "1". Not sure if people are interested but I can prepare something relevant for the same meetup: "Remote developer's guide to job hunting". I have a recent experience I could share. Maybe some useful resources too. Not everybody is looking for a job but I'm pretty sure many people are considering this as a possibility for the future. I can open a separate PR to get my votes, what do you think?

**Comment by Drelos** [comment]
I would propose you to open a new PR for this and is interesting for sure.  This topic for sure will take whole day
1. Tools/Processes/Best practices for remote development teams
2. Remote job hunting guidelines
3. Pros and cons of remote working (any one who has worked or is working remotely can present)

**Comment by mariosk** [comment]
Sure no problem, opening a new PR.

**Comment by jimmykarily** [comment]
Moved these topics (+ others) to #2. Lets cast our votes there.

**Pull request closed without merging**
